[build]
  base = "packages/backend"
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = false
